{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-ha.postgresql" . }}-metrics
  labels: {{ include "postgresql-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  annotations: {{ toYaml .Values.metrics.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9187
    targetPort: metrics
  selector: {{ include "postgresql-ha.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
