{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "postgresql-ha.pgpool" . }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "postgresql-ha.fullname" . }}
  labels: {{ include "postgresql-ha.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        backend:
          serviceName: {{ $serviceName | quote }}
          servicePort: postgresql
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}
